// Code generated by protoc-gen-go.
// source: response.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	response.proto

It has these top-level messages:
	ServerResponse
	Error
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerResponse struct {
	Result []byte `protobuf:"bytes,1,opt,name=Result,proto3" json:"Result,omitempty"`
	Error  *Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *ServerResponse) Reset()                    { *m = ServerResponse{} }
func (m *ServerResponse) String() string            { return proto1.CompactTextString(m) }
func (*ServerResponse) ProtoMessage()               {}
func (*ServerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ServerResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *ServerResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	Code    int64  `protobuf:"varint,1,opt,name=Code" json:"Code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto1.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Error) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto1.RegisterType((*ServerResponse)(nil), "proto.ServerResponse")
	proto1.RegisterType((*Error)(nil), "proto.Error")
}

func init() { proto1.RegisterFile("response.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 143 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x3e,
	0x5c, 0x7c, 0xc1, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0x41, 0x50, 0x69, 0x21, 0x31, 0x2e, 0xb6, 0xa0,
	0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x28, 0x4f, 0x48, 0x89,
	0x8b, 0x35, 0xb5, 0xa8, 0x28, 0xbf, 0x48, 0x82, 0x49, 0x81, 0x51, 0x83, 0xdb, 0x88, 0x07, 0x62,
	0x8e, 0x9e, 0x2b, 0x48, 0x2c, 0x08, 0x22, 0xa5, 0x64, 0xca, 0xc5, 0x0a, 0xe6, 0x0b, 0x09, 0x71,
	0xb1, 0x38, 0xe7, 0xa7, 0xa4, 0x82, 0x8d, 0x60, 0x0e, 0x02, 0xb3, 0x85, 0x24, 0xb8, 0xd8, 0x7d,
	0x53, 0x8b, 0x8b, 0x13, 0xd3, 0x53, 0xc1, 0x46, 0x70, 0x06, 0xc1, 0xb8, 0x49, 0x6c, 0x60, 0xa3,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1d, 0xc7, 0x99, 0xf7, 0xa4, 0x00, 0x00, 0x00,
}
